/**
 * Generates docs/ipc-api.md by parsing ipcMain.handle registrations
 * from src/main/ipc/*.ts. Run with: npx tsx scripts/generate-ipc-doc.ts
 */
import fs from 'node:fs';
import path from 'node:path';

const IPC_DIR = path.resolve(__dirname, '../src/main/ipc');
const IPC_CHANNELS = path.resolve(__dirname, '../src/shared/ipc-channels.ts');
const OUTPUT = path.resolve(__dirname, '../docs/ipc-api.md');

interface HandlerEntry {
  channel: string;       // e.g. 'blog:list'
  channelConst: string;  // e.g. 'IPC.BLOG_LIST'
  params: string;        // e.g. '_event, filters'
  returnType: string;    // e.g. '{ success, data }'
  file: string;          // e.g. 'blog.ts'
  isOn: boolean;         // ipcMain.on vs ipcMain.handle
}

function parseHandlers(): HandlerEntry[] {
  const entries: HandlerEntry[] = [];
  const files = fs.readdirSync(IPC_DIR).filter((f) => f.endsWith('.ts'));

  for (const file of files) {
    const content = fs.readFileSync(path.join(IPC_DIR, file), 'utf-8');
    // Match: ipcMain.handle(IPC.XXX, async (_event, param1, param2) => {
    const handleRe = /ipcMain\.(handle|on)\(\s*(\w+)\.(\w+)\s*,\s*(?:async\s*)?\(([^)]*)\)\s*(?::\s*([^{]+))?\s*=>/g;
    let m;
    while ((m = handleRe.exec(content)) !== null) {
      const [, method, obj, channelConst, paramsRaw] = m;
      const params = paramsRaw
        .replace(/^_event\s*(?:,\s*)?/, '')
        .replace(/\s+/g, ' ')
        .trim();
      // Try to resolve the channel string value
      let channel = `${obj}.${channelConst}`;
      // Read IPC constant value from ipc-channels.ts
      try {
        const channelsContent = fs.readFileSync(IPC_CHANNELS, 'utf-8');
        const constRe = new RegExp(`${channelConst}\\s*:\\s*['\"]([^'\"]+)['\"]`);
        const cm = constRe.exec(channelsContent);
        if (cm) channel = cm[1];
      } catch { /* keep the const name */ }

      entries.push({
        channel,
        channelConst: `${obj}.${channelConst}`,
        params: params || '(none)',
        returnType: '{ success: boolean; data?: T; error?: string }',
        file,
        isOn: method === 'on',
      });
    }
  }

  return entries;
}

function generate(): void {
  const entries = parseHandlers();

  // Group by file
  const byFile = new Map<string, HandlerEntry[]>();
  for (const e of entries) {
    if (!byFile.has(e.file)) byFile.set(e.file, []);
    byFile.get(e.file)!.push(e);
  }

  let md = `# IPC API Reference\n\n`;
  md += `> Auto-generated by \`scripts/generate-ipc-doc.ts\`\n`;
  md += `> Last updated: ${new Date().toISOString().substring(0, 10)}\n`;
  md += `> Total channels: ${entries.length}\n\n`;

  for (const [file, fileEntries] of [...byFile.entries()].sort()) {
    md += `## ${file}\n\n`;
    md += `| Channel | Direction | Parameters | Returns |\n`;
    md += `|---------|-----------|------------|--------|\n`;
    for (const e of fileEntries) {
      const dir = e.isOn ? 'renderer→main' : 'renderer→main';
      md += `| \`${e.channel}\` | ${dir} | ${e.params} | ${e.returnType} |\n`;
    }
    md += `\n`;
  }

  // Channel index
  md += `## Channel Index\n\n`;
  const allSorted = [...entries].sort((a, b) => a.channel.localeCompare(b.channel));
  for (const e of allSorted) {
    md += `- \`${e.channel}\` — \`${e.file}\`\n`;
  }
  md += `\n`;

  const dir = path.dirname(OUTPUT);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(OUTPUT, md, 'utf-8');
  console.log(`[IPC Doc] Generated ${OUTPUT} — ${entries.length} channels`);
}

generate();
